sudo: required
services:
  - docker
install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker version
  - docker-compose version
  - rm docker-compose.override.yml
  - docker-compose pull
  - docker-compose build
  - docker-compose up -d
script:
  - docker-compose run --rm --volume "$PWD/dist:/src/dist" dbmate make build
  - docker-compose run --rm dbmate make wait
  - docker-compose run --rm dbmate make test
  - docker-compose run --rm dbmate make lint
  - docker build -t dbmate .
  - docker run --rm dbmate --help
deploy:
  provider: releases
  api_key:
    secure: cBeY8/45cAuuZMyTIFe3/8YC7UoL3t7CQsJTjtKT/EOFs52vTZHNgGyrdPAgxECKAnMwmnjKat4qlYgGfLdBFZZN9ZqpXPBDaEkG9UQKg1kn4N9iYKzufJ1M4b8VdEVpqBLNFA2w+2/Kna8hQ4QM5Ds+CznJXZnqytq2zkO8Don7cfqK1HTh2OyGq/4GDcOVCdADatUK+KHOohTPSmkgAzCfZOe/IygFwpmvqW0PM9J8kj3oecHU4ISQ6uomPE4xvugnyYXp0TmKpftD1sM/exm4nYMIrM6XMWo3DLohcZmKYkTGyHCzBu/bltDkjR+WL6ABDkT4MKqIDrRHPqvuZ7QGyM1paxhKNdE9GS5osbIwvQED1rn0KToukNSia48QikESIZhAyQnrEvTy67K6V7IQaUk3q+FWy/+NgSTU4IoFnlcHrPSLu5EusTWu6LGA+9auBqsV11gkkJ87eBVRwWAd7a1UYOHYPdjQvdVm0rzJQxNFwF/dVYSVa9uMQpVkKcpzC+n8mOxnMMS8cLs2oYy1eLynVXtqHXYYqRFk5QGjHrd7TF4AnOF0wip9goArnmyORyKTsEN4KiVu2EQ6CMSpAmw1pbRsAZ2wcSewYE7xdEDURcLHn/99E4Bfy/CPnluppS4CGqE1ASpINh6rbapJPN8cuXa4t59J4f+iUMI=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
    repo: csuriano23/dbmate-oracle
